set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm-ghostty:RGB'
set -s escape-time 0

set -g status-style 'bg=#333333 fg=#5eacd3'
set -g @hostname "Mana"
set -g status-right '#{@hostname} | %H:%M %a %h %d'

bind r source-file ~/.tmux.conf
set -g base-index 1

set -g mouse on
setw -g mode-keys vi
set -g history-limit 100000

# new window always opens at the "terminal" window's path, not the last active pane's
bind c run-shell 'tmux new-window -t "#{session_name}" -c "$(tmux display-message -p -t "#{session_name}:terminal" "#{pane_current_path}")"'